[package]
name = "q565-c"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib"]

[features]
default = ["std"]
std = []

[dependencies]
q565 = { path = "../q565", default-features = false }
