name: CI Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  building:
    name: Building
    strategy:
      matrix:
        rust: [stable]
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: "thumbv6m-none-eabi"
      - run: cargo build --workspace
      - run: cargo build -p q565-c --profile clib --no-default-features --target thumbv6m-none-eabi
  linting:
    name: Linting and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy, rustfmt"
      - run: cargo fmt -- --check
      - run: cargo clippy --all-features -- --deny=warnings
  testing:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
